:: Artists and galleries
start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
start "" "https://rossdraws.deviantart.com/gallery/"
start "" "https://kate-fox.deviantart.com/gallery/"
start "" "https://sakimichan.deviantart.com/gallery/"
start "" "https://nsio.deviantart.com/gallery/"
start "" "https://kachima.deviantart.com/gallery/"

start "" "https://ryky.deviantart.com/gallery/"
start "" "https://zombiesmile.deviantart.com/gallery/"
start "" "https://robotcatart.deviantart.com/gallery/"
start "" "https://grooooovy.deviantart.com/gallery/"
start "" "https://chacckco.deviantart.com/gallery/"
start "" "https://edwinhuang.deviantart.com/gallery/"
start "" "https://endling.deviantart.com/gallery/"